spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lre_thrustchamber?characterEncoding=utf-8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: lre-thrustchamber
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
#    instance:
#      prefer-ip-address: true
server:
  port: 10085



